### ISSUE TITLE
I want to report your paper for fraud

### ISSUE THREAD

**Issue by TpBlair** [YujieMo/SUGRL#7]
I want to report your paper for fraud. The code is different from your paper

![image](https://user-images.githubusercontent.com/51107495/199784138-49e3ab1e-510c-4864-b96a-fbf88d687dc2.png)

![image](https://user-images.githubusercontent.com/51107495/199784189-9e41ff25-760f-433b-a131-864e3c983a72.png)

**Comment by YujieMo** [comment]
> I want to report your paper for fraud. The code is different from your paper
> 
> ![image](https://user-images.githubusercontent.com/51107495/199784138-49e3ab1e-510c-4864-b96a-fbf88d687dc2.png)
> 
> ![image](https://user-images.githubusercontent.com/51107495/199784189-9e41ff25-760f-433b-a131-864e3c983a72.png)

Hi, thanks for your interest in SUGRL, in fact, the framework diagram and the code are consistent. In SUGRL, the anchor samples are output by the MLP, and the positive samples are output by the GCN. As we know, GCN consists of two parts, i.e., linear layer and convolutional layer. In the implementation, we make the linear layer of GCN share the parameter matrix with the MLP encoder, as in the code.
